---
- name: checking template
  hosts: all
  become: true
  vars:
    anonymous_enable: yes
    local_enable: yes
  tasks: 
   - name: installing vsftpd
     yum: 
      name: vsftpd
   - name: copying template to conf
     template: 
        src: vsftpd.j2
        dest: /etc/vsftpd/vsftpd.conf
